name: glint
description: "A glint/shimmer reusable widget that can help you display bring simple yet loading animation while keeping it's usage extremely simple."
version: 0.0.1
homepage: https://pub.dev/packages/glint
issue_tracker: https://github.com/ghifariakbar01/glint/issues
repository: https://github.com/ghifariakbar01/glint
topics:
  - loading
  - shimmer
  - skeleton

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# flutter:
